title   = "Antagonistic Dual-Wavelength Tomographic Volumetric Additive Manufacturing"
authors = "Quinten Thijssen, Felix Wechsler, Antonio J. Ortega, Joshua A. Carroll, Christophe Moser, Sandra Van Vlierberghe, Christopher Barner-Kowollik"
venue   = "ChemRxiv preprint, 2026"
link    = "https://chemrxiv.org/doi/abs/10.26434/chemrxiv.15006647/v1"
link_label = "doi.org/10.26434/chemrxiv.15006647/v1"
desc    = "Dual color TVAM to control both polymerization and inhibition"
image   = "/assets/antagonistic_TVAM.jpg"
