title   = "Overprinting with Tomographic Volumetric Additive Manufacturing"
authors = "<b>Felix Wechsler</b>, Viola Sgarminato, Riccardo Rizzo, Baptiste Nicolet, Wenzel Jakob, Christophe Moser"
venue   = "Accepted at Nature Communications"
link    = "https://arxiv.org/abs/2507.13842"
link_label = "arXiv:2507.13842"
desc    = "High-quality overprinting for TVAM which considers optical effects such as scattering, reflection, refraction or attenuation."
image   = "/assets/overprinting.jpg"
