title   = "Overprinting with Tomographic Volumetric Additive Manufacturing"
authors = "<b>Felix Wechsler</b>, Viola Sgarminato, Riccardo Rizzo, Baptiste Nicolet, Wenzel Jakob, Christophe Moser"
venue   = "Nature Communications"
link    = "https://www.nature.com/articles/s41467-026-73477-3"
link_label = "doi.org/10.1038/s41467-026-73477-3"
desc    = "High-quality overprinting for TVAM which considers optical effects such as scattering, reflection, refraction or attenuation."
image   = "/assets/overprinting.jpg"
